### ISSUE TITLE
Game doesn't launch correctly in 32:9

### ISSUE THREAD

**Issue by Dayfut** [crocokyle/Valorant-Ultrawide-Fix#4]
[ValorantLauncher_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5864133/ValorantLauncher_log.log)
[install_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5864134/install_log.log)
[SysSetup_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5864135/SysSetup_log.log)

Game just doesn't launch for me.  Is it because of my monitor resolution of 5120x1440?

**Comment by crocokyle** [comment]
Hello, your log files look okay, but I have pushed out quite a few updates since you tested this. Could you try to download it once more and post the updated logs? 

The latest version logs information in a lot more detail so that I can troubleshoot more advanced issues. 

It is possible that 5120x1440 will have trouble. I only have a 21:9 to test on so I'm not yet sure what will happen on the larger ratios.

**Comment by Dayfut** [comment]
[install_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5871013/install_log.log)
[SysSetup_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5871014/SysSetup_log.log)
[ValorantLauncher_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5871015/ValorantLauncher_log.log)

Okay so the icon showed up this time and I was able to launch the game.  Like you said, the larger aspect ratio didn't work.  Still get a stretched image instead of cropped when I load into the shooting range to test.  Keep up the good work though.

**Comment by crocokyle** [comment]
Okay great, good to hear. Thanks for the logs, it really helps since I can't test 32:9. I didn't realize it is stretching on the larger ratios. It sounds like it may be a limitation in the binary rather than something wrong with the script, but I will keep testing. Another idea I had was if the monitor is wider than 21:9, calculate the 21:9 ratio that would fit into your resolution and center it so that at least you can gain some width. I'm going to close this issue, but feel free to check back or comment in issue #6 for progress on the wider ratios. 

BTW, might want to try loading into an actual game...It may have just been a fluke, but I tried out the shooting range today on another PC and it was only in 16:9, but loading an actual game was 21:9.
