### ISSUE TITLE
Multiple Valorant Accounts or Installations

### ISSUE THREAD

**Issue by mr2cam** [crocokyle/Valorant-Ultrawide-Fix#8]
Still see black bars, multi monitor setup, autohide not enabled, tried
[SysSetup_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5906732/SysSetup_log.log)
[ValorantLauncher_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5906733/ValorantLauncher_log.log)

 adding monitors 0, 1, 2 and 3 and still have black bars

**Comment by Mr-Stetson** [comment]
I do have the same problem, could it be because of I (or we) have a monitor above the main one?
My logs:
[SysSetup_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5921665/SysSetup_log.log)
[ValorantLauncher_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5921667/ValorantLauncher_log.log)
[install_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5921668/install_log.log)

**Comment by crocokyle** [comment]
@mr2cam Yours is because you either use multiple Valorant accounts or you have an extra installation folder hanging around. You can see this here in #3 

I will try to work on this when I can, but a workaround for now would be to delete one of the tokenized folders in 
```
C:\Users\<your_username>\AppData\Local\VALORANT\Saved\Config\
```
You currently have two:
```
69803db8-3a97-5c68-aee3-e98d9fe57603
a702b4bc-b089-5b47-b788-1d16196911de
```

**Only do this if you are certain it's an old account you no longer use.** It could prevent the game from loading and you would need to reinstall Valorant.

**Comment by crocokyle** [comment]
@Jugistyler  Your issue is different. I'm going to need to look into this, but I will open a separate issue for this one here: #10 

Somehow it is reversing your Height and Width
